const countries = [
{country:'그리스',budget:[4, 5],period:[3],preferStyle:[2],nangMan:[0],continent:'유럽',pkgVSfree:[2], food:[1]},
{country:'괌',budget:[3, 4, 5],period:[1, 2],preferStyle:[2],nangMan:[0],continent:'오세아니아',pkgVSfree:[2], food:[0]},
{country:'네덜란드',budget:[4, 5],period:[3],preferStyle:[2],nangMan:[0],continent:'유럽',pkgVSfree:[2], food:[0]},
{country:'네팔',budget:[3, 4],period:[1, 2],preferStyle:[2],nangMan:[0],continent:'아시아',pkgVSfree:[2], food:[0]},
{country:'노르웨이',budget:[4, 5],period:[3],preferStyle:[2],nangMan:[0],continent:'유럽',pkgVSfree:[2], food:[0]},
{country:'뉴질랜드',budget:[3, 4],period:[2, 3],preferStyle:[2],nangMan:[0],continent:'오세아니아',pkgVSfree:[2], food:[0]},
{country:'남아프리카 공화국',budget:[3, 4],period:[2, 3],preferStyle:[3],nangMan:[0],continent:'아프리카',pkgVSfree:[2], food:[0]},
{country:'남극',budget:[5],period:[2, 3],preferStyle:[3],nangMan:[5],continent:'남극',pkgVSfree:[2], food:[0]},
{country:'독일',budget:[4, 5],period:[3],preferStyle:[1],nangMan:[0],continent:'유럽',pkgVSfree:[1], food:[0]},
{country:'덴마크',budget:[4, 5],period:[3],preferStyle:[1],nangMan:[0],continent:'유럽',pkgVSfree:[1], food:[0]},
{country:'대만',budget:[1, 2],period:[1, 2],preferStyle:[1],nangMan:[0],continent:'아시아',pkgVSfree:[1], food:[1]},
{country:'룩셈부르크',budget:[4, 5],period:[3],preferStyle:[2],nangMan:[0],continent:'유럽',pkgVSfree:[2], food:[0]},
{country:'러시아',budget:[3, 4],period:[1],preferStyle:[2],nangMan:[0],continent:'유럽/아시아',pkgVSfree:[2], food:[0]},
{country:'라오스',budget:[1, 2],period:[1],preferStyle:[2],nangMan:[0],continent:'아시아',pkgVSfree:[2], food:[1]},
{country:'라트비아',budget:[4, 5],period:[3],preferStyle:[2],nangMan:[0],continent:'유럽',pkgVSfree:[2], food:[1]},
{country:'루마니아',budget:[4, 5],period:[3],preferStyle:[2],nangMan:[0],continent:'유럽',pkgVSfree:[2], food:[0]},
{country:'리투아니아',budget:[4, 5],period:[3],preferStyle:[1, 2],nangMan:[0],continent:'유럽',pkgVSfree:[1], food:[1]},
{country:'미국',budget:[4, 5],period:[2, 3],preferStyle:[1, 2],nangMan:[0],continent:'북미',pkgVSfree:[1], food:[0]},
{country:'몽골',budget:[1, 2],period:[1, 2],preferStyle:[3],nangMan:[5],continent:'아시아',pkgVSfree:[1, 2], food:[1]},
{country:'몰타',budget:[4, 5],period:[1],preferStyle:[2],nangMan:[0],continent:'유럽',pkgVSfree:[2], food:[0]},
{country:'몰디브',budget:[4, 5],period:[1],preferStyle:[2],nangMan:[0],continent:'아시아',pkgVSfree:[2], food:[0]},
{country:'모로코',budget:[3, 4, 5],period:[3],preferStyle:[2],nangMan:[0],continent:'아프리카',pkgVSfree:[2], food:[1]},
{country:'모나코',budget:[4, 5],period:[3],preferStyle:[2],nangMan:[0],continent:'유럽',pkgVSfree:[2], food:[0]},
{country:'멕시코',budget:[4, 5],period:[1, 2],preferStyle:[1, 3],nangMan:[0],continent:'북미',pkgVSfree:[1], food:[1]},
{country:'말레이시아',budget:[1, 2, 3],period:[1],preferStyle:[2],nangMan:[0],continent:'아시아',pkgVSfree:[2], food:[1]},
{country:'몬테네그로',budget:[4, 5],period:[3],preferStyle:[2],nangMan:[0],continent:'유럽',pkgVSfree:[2], food:[0]},
{country:'미얀마',budget:[2, 3],period:[1, 2],preferStyle:[2],nangMan:[0],continent:'아시아',pkgVSfree:[2], food:[0]},
{country:'모리셔스',budget:[4, 5],period:[1],preferStyle:[2],nangMan:[0],continent:'아프리카',pkgVSfree:[2], food:[0]},
{country:'마카오',budget:[1, 2],period:[1, 2],preferStyle:[1],nangMan:[0],continent:'아시아',pkgVSfree:[1], food:[0]},
{country:'브라질',budget:[4, 5],period:[3],preferStyle:[2],nangMan:[0],continent:'남미',pkgVSfree:[2], food:[1]},
{country:'불가리아',budget:[4, 5],period:[3],preferStyle:[2],nangMan:[0],continent:'유럽',pkgVSfree:[2], food:[0]},
{country:'볼리비아',budget:[3, 4, 5],period:[3],preferStyle:[2],nangMan:[0],continent:'남미',pkgVSfree:[2], food:[0]},
{country:'벨기에',budget:[4, 5],period:[3],preferStyle:[1],nangMan:[0],continent:'유럽',pkgVSfree:[1], food:[0]},
{country:'보스니아 헤르체고비나',budget:[4, 5],period:[3],preferStyle:[1, 2],nangMan:[0],continent:'유럽',pkgVSfree:[2], food:[0]},
{country:'베트남',budget:[1, 2],period:[1],preferStyle:[2],nangMan:[0],continent:'아시아',pkgVSfree:[2], food:[1]},
{country:'보라보라 섬',budget:[3, 4, 5],period:[1],preferStyle:[2],nangMan:[5],continent:'오세아니아',pkgVSfree:[2], food:[0]},
{country:'브루나이',budget:[2, 3, 4],period:[1],preferStyle:[2],nangMan:[0],continent:'아시아',pkgVSfree:[2], food:[0]},
{country:'싱가포르',budget:[3, 4],period:[1, 2],preferStyle:[1],nangMan:[0],continent:'아시아',pkgVSfree:[1], food:[0]},
{country:'슬로베니아',budget:[4, 5],period:[3],preferStyle:[1],nangMan:[0],continent:'유럽',pkgVSfree:[1], food:[0]},
{country:'슬로바키아',budget:[4, 5],period:[3],preferStyle:[1, 2],nangMan:[0],continent:'유럽',pkgVSfree:[2], food:[0]},
{country:'스페인',budget:[4, 5],period:[3],preferStyle:[1],nangMan:[0],continent:'유럽',pkgVSfree:[1], food:[1]},
{country:'스위스',budget:[4, 5],period:[3],preferStyle:[2],nangMan:[0],continent:'유럽',pkgVSfree:[2], food:[0]},
{country:'스웨덴',budget:[4, 5],period:[3],preferStyle:[1, 2],nangMan:[0],continent:'유럽',pkgVSfree:[2], food:[0]},
{country:'세르비아',budget:[4, 5],period:[3],preferStyle:[1],nangMan:[0],continent:'유럽',pkgVSfree:[1], food:[0]},
{country:'세이셸',budget:[4, 5],period:[1],preferStyle:[2],nangMan:[0],continent:'아프리카',pkgVSfree:[2], food:[0]},
{country:'스리랑카',budget:[1, 2, 3],period:[1],preferStyle:[2, 3],nangMan:[0],continent:'아시아',pkgVSfree:[2], food:[1]},
{country:'사이판',budget:[2, 3],period:[1],preferStyle:[1, 2],nangMan:[0],continent:'오세아니아',pkgVSfree:[2], food:[0]},
{country:'일본',budget:[1, 2],period:[1],preferStyle:[1],nangMan:[0],continent:'아시아',pkgVSfree:[1, 2], food:[0]},
{country:'인도네시아',budget:[2, 3],period:[1],preferStyle:[2],nangMan:[0],continent:'아시아',pkgVSfree:[2], food:[1]},
{country:'인도',budget:[3, 4],period:[2, 3],preferStyle:[3],nangMan:[0],continent:'아시아',pkgVSfree:[2], food:[1]},
{country:'이탈리아',budget:[4, 5],period:[3],preferStyle:[1],nangMan:[0],continent:'유럽',pkgVSfree:[1], food:[1]},
{country:'이집트',budget:[4, 5],period:[3],preferStyle:[1, 3],nangMan:[0],continent:'아프리카',pkgVSfree:[1], food:[1]},
{country:'이스라엘',budget:[3, 4],period:[1, 2],preferStyle:[1],nangMan:[0],continent:'아시아',pkgVSfree:[2], food:[1]},
{country:'우루과이',budget:[4, 5],period:[3],preferStyle:[1, 2],nangMan:[0],continent:'남미',pkgVSfree:[2], food:[0]},
{country:'우크라이나',budget:[4, 5],period:[3],preferStyle:[1, 2],nangMan:[0],continent:'유럽',pkgVSfree:[2], food:[0]},
{country:'영국',budget:[4, 5],period:[3],preferStyle:[1],nangMan:[0],continent:'유럽',pkgVSfree:[1], food:[0]},
{country:'오스트리아',budget:[4, 5],period:[3],preferStyle:[1, 2],nangMan:[5],continent:'유럽',pkgVSfree:[1], food:[0]},
{country:'아일랜드',budget:[4, 5],period:[3],preferStyle:[2],nangMan:[0],continent:'유럽',pkgVSfree:[2], food:[0]},
{country:'아이슬란드',budget:[4, 5],period:[1],preferStyle:[2],nangMan:[0],continent:'유럽',pkgVSfree:[2], food:[0]},
{country:'아르헨티나',budget:[4, 5],period:[3],preferStyle:[1, 2],nangMan:[0],continent:'남미',pkgVSfree:[2], food:[0]},
{country:'아랍에미리트',budget:[4, 5],period:[1, 2],preferStyle:[1],nangMan:[0],continent:'아시아',pkgVSfree:[1], food:[1]},
{country:'아제르바이잔',budget:[4, 5],period:[3],preferStyle:[2],nangMan:[0],continent:'유럽',pkgVSfree:[2], food:[1]},
{country:'에스토니아',budget:[4, 5],period:[3],preferStyle:[1, 2, 3],nangMan:[0],continent:'유럽',pkgVSfree:[2], food:[0]},
{country:'에티오피아',budget:[3, 4, 5],period:[3],preferStyle:[3],nangMan:[0],continent:'아프리카',pkgVSfree:[2], food:[1]},
{country:'요르단',budget:[3, 4],period:[1, 2],preferStyle:[1],nangMan:[0],continent:'아시아',pkgVSfree:[1, 2], food:[1]},
{country:'우즈베키스탄',budget:[3, 4, 5],period:[1, 2],preferStyle:[1],nangMan:[0],continent:'아시아',pkgVSfree:[1], food:[0]},
{country:'조지아',budget:[4, 5],period:[3],preferStyle:[2],nangMan:[0],continent:'유럽',pkgVSfree:[2], food:[0]},
{country:'중국',budget:[1, 2, 3],period:[1],preferStyle:[1],nangMan:[0],continent:'아시아',pkgVSfree:[1], food:[1]},
{country:'체코',budget:[4, 5],period:[3],preferStyle:[1],nangMan:[0],continent:'유럽',pkgVSfree:[1], food:[0]},
{country:'칠레',budget:[4, 5],period:[3],preferStyle:[2],nangMan:[0],continent:'남미',pkgVSfree:[1], food:[0]},
{country:'크로아티아',budget:[4, 5],period:[3],preferStyle:[2],nangMan:[0],continent:'유럽',pkgVSfree:[2], food:[0]},
{country:'쿠바',budget:[4, 5],period:[1, 2],preferStyle:[1, 2],nangMan:[0],continent:'북미',pkgVSfree:[2], food:[0]},
{country:'콜롬비아',budget:[4, 5],period:[3],preferStyle:[1],nangMan:[0],continent:'남미',pkgVSfree:[2], food:[1]},
{country:'케냐',budget:[3, 4],period:[3],preferStyle:[3],nangMan:[5],continent:'남미',pkgVSfree:[2], food:[0]},
{country:'캐나다',budget:[4, 5],period:[2, 3],preferStyle:[2],nangMan:[0],continent:'북미',pkgVSfree:[1, 2], food:[0]},
{country:'캄보디아',budget:[2, 3],period:[2],preferStyle:[1, 3],nangMan:[0],continent:'아시아',pkgVSfree:[2], food:[1]},
{country:'카타르',budget:[3, 4, 5],period:[1, 2],preferStyle:[1],nangMan:[0],continent:'아시아',pkgVSfree:[1], food:[0]},
{country:'카자흐스탄',budget:[3, 4, 5],period:[1, 2],preferStyle:[1],nangMan:[0],continent:'아시아',pkgVSfree:[1], food:[1]},
{country:'태국',budget:[1, 2],period:[1],preferStyle:[1, 2],nangMan:[0],continent:'아시아',pkgVSfree:[2], food:[1]},
{country:'튀르키예',budget:[4, 5],period:[1, 2],preferStyle:[1, 2],nangMan:[0],continent:'아시아/유럽',pkgVSfree:[2], food:[0]},
{country:'탄자니아',budget:[3, 4, 5],period:[3],preferStyle:[2, 3],nangMan:[0],continent:'아프리카',pkgVSfree:[2], food:[1]},
{country:'필리핀',budget:[1, 2, 3],period:[1],preferStyle:[2],nangMan:[0],continent:'아시아',pkgVSfree:[2], food:[1]},
{country:'핀란드',budget:[4, 5],period:[3],preferStyle:[2],nangMan:[0],continent:'유럽',pkgVSfree:[2], food:[0]},
{country:'피지',budget:[2, 3, 4],period:[1],preferStyle:[2],nangMan:[0],continent:'오세아니아',pkgVSfree:[2], food:[0]},
{country:'프랑스',budget:[4, 5],period:[3],preferStyle:[1],nangMan:[0],continent:'유럽',pkgVSfree:[1], food:[0]},
{country:'폴란드',budget:[4, 5],period:[3],preferStyle:[1],nangMan:[0],continent:'유럽',pkgVSfree:[1], food:[0]},
{country:'포르투갈',budget:[4, 5],period:[3],preferStyle:[1],nangMan:[0],continent:'유럽',pkgVSfree:[1], food:[0]},
{country:'페루',budget:[4, 5],period:[3],preferStyle:[1, 3],nangMan:[0],continent:'남미',pkgVSfree:[1], food:[1]},
{country:'팔라우',budget:[3, 4],period:[1],preferStyle:[2],nangMan:[5],continent:'오세아니아',pkgVSfree:[2], food:[0]},
{country:'호주',budget:[3, 4, 5],period:[2, 3],preferStyle:[2],nangMan:[0],continent:'오세아니아',pkgVSfree:[2], food:[0]},
{country:'헝가리',budget:[4, 5],period:[3],preferStyle:[1, 2],nangMan:[0],continent:'유럽',pkgVSfree:[2], food:[0]},
{country:'홍콩',budget:[2, 3],period:[1],preferStyle:[1],nangMan:[0],continent:'아시아',pkgVSfree:[1], food:[0]}]
